### ISSUE TITLE
files

### ISSUE THREAD

**Issue by Celllnside** [DrNseven/D3D11-Worldtoscreen-Finder#32]
so, i have all; the files for everthing sethook and d3d11, but they are still in file form. how to i make d3d11 into a exe and sethook into a dll..

**Comment by Celllnside** [comment]
i meant d3d11 into a DLL and sethook into a exe***

**Comment by Kek5chen** [comment]
you need to compile them to a Dynamic Link Library - File and edit the code in them to be useable.

**Comment by Celllnside** [comment]
> Dynamic Link Library

what code do i edit, still confuzed

**Comment by Celllnside** [comment]
> you need to compile them to a Dynamic Link Library - File and edit the code in them to be useable.

please just add me on discord theres alot i need to ask, i still dont know how to make sethook a exe

**Comment by Kek5chen** [comment]
Hello @Celllnside ,
If you have no idea what you are doing or should do with this, you should start learning game hacking with c and c++.

GuidedHacking has a really good forum for that. Here is a link. https://guidedhacking.com/forums/c-c-coding-and-game-hacking.36/

Since there is no issue with this repository to be seen in this ticket i hereby request you to close this issue as this is nothing we can assist you with.
No further information is needed.

Best regards,
kek5chen
